baseURL: 'https://walkergriggs.com'
languageCode: 'en-us'
title: 'Walker Griggs'
disableKinds: ["taxonomy"]
ignoreErrors: ["error-disable-taxonomy"]
pluralizeListTitles: false


params:
        header: Walker Griggs is a video and distributed systems engineer, focused on developer-first platforms. He is based in San Francisco, California.
        twitter: "WebDevScaresMe"
        author:
                email: "hello@walkergriggs.com"

permalinks:
        posts: "/:year/:month/:day/:filename"
        pages: "/:slug"

menu:
        main:
                - name: Home.
                  url: ""
                  weight: 1
                - name: Writing.
                  url: "posts/"
                  weight: 2
                - name: Reading.
                  url: "reading/"
                  weight: 3
                - name: Projects.
                  url: "https://github.com/WalkerGriggs"
                  weight: 4
                - name: RSS.
                  url: "/index.xml"
                  weight: 5


markup:
        goldmark:
                renderer:
                        unsafe: true
        highlight:
                anchorLineNos: false
                codeFences: true
                guessSyntax: false
                hl_Lines: ""
                hl_inline: false
                lineAnchors: ""
                lineNoStart: 1
                lineNos: false
                lineNumbersInTable: true
                noClasses: true
                noHl: false
                style: dracula
                tabWidth: 4